### ISSUE TITLE
猴子的脸改成不透明的？

### ISSUE THREAD

**Issue by Senorsen** [GyrosWorkshop/WukongDesign#1]
现在是这样，稍微有点儿僵：
![image](https://cloud.githubusercontent.com/assets/4176091/25071102/b24559e4-22e1-11e7-9007-ccdcce963367.png)

**Comment by LittleAprilFool** [comment]
好。。。那话说Github Bilibili之类的icon在你的浏览器里是啥样的呀。。。（（感觉这事儿得怪用户。。

**Comment by aoli-al** [comment]
我很好奇这个图标是在哪里出现的。。。怎么感觉是在任务栏。。。

**Comment by Senorsen** [comment]
![image](https://cloud.githubusercontent.com/assets/4176091/25078048/0d9a20e2-2362-11e7-9274-f8dff21b5834.png)
确实是任务栏
怪我咯（

**Comment by Senorsen** [comment]
但 wukong 这个小鼻孔有点毒…
